site_name: Engine-Antiginx Documentation 
repo_name: prawo-i-piesc/engine-antiginx
repo_url: https://github.com/prawo-i-piesc/engine-antiginx
site_url: https://prawo-i-piesc.github.io/engine-antiginx/
strict: true


theme:
  name: material

  icon:
    repo: fontawesome/brands/git-alt

  font:
    text: Roboto
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: black
      accent: indigo

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: blue
      accent: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips

plugins: 
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2-4

nav:
  - Engine Antiginx: index.md
  - Quick Start: 
    - Quick Start: QuickStart/QuickStart.md
    - CLI: QuickStart/CLI.md
    - Docker: QuickStart/Docker.md
    - Docker-Compose: QuickStart/DockerCompose.md
  - App Documentation:
    - App: App/index.md
    - CVE: App/CVE/index.md
    - Errors: App/Errors/index.md
    - Execution: App/execution/index.md
    - GlobalHandler: App/GlobalHandler/index.md
    - Helpers: App/Helpers/index.md
    - HTTP: App/HTTP/index.md
    - Parameter-Parser: App/parser/index.md
    - Registry: App/Registry/index.md
    - Reporter: App/Reporter/index.md
    - Runner: App/Runner/index.md
    - Site Tests:
      - Framework: App/SiteTests/index.md
      - Bot Protection: App/SiteTests/BotProtectionTest/index.md
      - Content Security Policy: App/SiteTests/CSPTest/index.md
      - Cookie Security:
        - Test: App/SiteTests/CookieSecurityTest/index.md
        - Modules: App/SiteTests/CookieSecurityTest/modules/index.md
      - Cross-Origin: App/SiteTests/CrossOriginTest/index.md
      - HSTS: App/SiteTests/HSTSTest/index.md
      - HTTPS: App/SiteTests/HTTPSTest/index.md
      - JS Obfuscation:
        - Test: App/SiteTests/JSObfuscationTest/index.md
        - Modules: App/SiteTests/JSObfuscationTest/modules/index.md
      - Permissions Policy: App/SiteTests/PermissionsPolicyTest/index.md
      - Phishing URL:
        - Test: App/SiteTests/PhishingURLTest/index.md
        - Modules: App/SiteTests/PhishingURLTest/modules/index.md
      - Referrer Policy: App/SiteTests/ReferrerPolicyTest/index.md
      - SSL Certificate: App/SiteTests/SSLCertificateSecurityTest/index.md
      - Server Header:
        - Test: App/SiteTests/ServerHeaderTest/index.md
        - Modules: App/SiteTests/ServerHeaderTest/modules/index.md
      - Sitemap Security:
        - Test: App/SiteTests/SitemapSecurityTest/index.md
        - Modules: App/SiteTests/SitemapSecurityTest/modules/index.md
      - X-Content-Type-Options: App/SiteTests/XContentTypeOptionsTest/index.md
      - X-Frame-Options: App/SiteTests/XFrameTest/index.md
  - Engined Documentation:
    - Daemon: Engined/index.md

copyright: "Copyright &copy; 2025 Antiginx Team. All rights reserved."

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prawo-i-piesc/engine-antiginx