name: Lint Verification
run-name: >-
    ${{ 
        github.event_name == 'pull_request' 
        && format('Lint Verification for CI: PR #{0} -> {1}', github.event.number, github.event.pull_request.title)
        ||
        github.event_name == 'push'
        && format('Lint Verification for CI: Merge -> {0}', github.event.head_commit.message)
    }}

on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches: [ "main" ]

permissions:
    contents: read

concurrency:
    group: ${{ github.event_name == 'pull_request' && format('{0}-pr-{1}', github.workflow, github.event.pull_request.number) || format('{0}-ref-{1}', github.workflow, github.ref) }}
    cancel-in-progress: true

jobs:
    lint-ci-test:
        name: Testing
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
        - name: 📥 Git -- Checkout repository
          uses: actions/checkout@v6

        - name: 📘 Go -- Set up
          uses: actions/setup-go@v6
          with:
            go-version-file: 'go.mod'
            cache: true

        - name: 🧪 Go -- Test Lint
          uses: golangci/golangci-lint-action@v9
          with:
            version: latest